### ISSUE TITLE
[Question] HiveField 0 - 255 exclusive to one class?

### ISSUE THREAD

**Issue by madqueendany** [leisim/hive#16]
In the example, if I want to register a class to a HiveType, I'd have to put `@HiveField(n)` to the fields that I want to store, right?

```
@HiveType()
class Dog {
  @HiveField(0)
  String name;

  @HiveField(1)
  int age;

  @HiveField(2)
  List<Person> friends;
}
```

What if I have another class that I want to store, like `Cat`?
```
@HiveType()
class Cat {
  @HiveField(3)
  String name;

  @HiveField(4)
  int age;

  @HiveField(5)
  List<Person> friends;
}
```

should the numbering continue, or it goes back to zero?

**Comment by leisim** [comment]
Yes, you should start at 0 for each class. I'll clarify the documentation and close this issue when it is done.

**Comment by madqueendany** [comment]
Great. Tried it out as well. It can go back to zero.

Thanks so far so good!
