### ISSUE TITLE
Time To Live

### ISSUE THREAD

**Issue by Solido** [leisim/hive#18]
I'd like to use Hive as a temporary cache for resources.

Setup would be done with a TTL field that can be set at the Box and write method level.

`box.putAll({'key1': 'value1', 42: 'life'}, ttl: const Duration(seconds:30))`

Is this a feature in the scope of Hive ?

Thanks

**Comment by leisim** [comment]
This is a very good idea. I don't know if it is possible but I'll think about how to implement this.

**Comment by Solido** [comment]
I've tinkered with something like this :

```
class Ephemere {
  final Duration defaultDuration;
  final Map<Object, dynamic> _cache;

  Ephemere(this.defaultDuration) : _cache = Map();

  dynamic get(Object key, Function defaultValue) {
    final rs = _cache[key] ?? defaultValue();
    return rs;
  }

  Future put(Object key, value, {Duration duration}) {
    Completer completer = Completer();
    _cache.putIfAbsent(key, () => value);

    Future.delayed(duration ?? defaultDuration, () {
      _cache.remove(key);
      completer.complete(value);
    });

    return completer.future;
  }
}
```

**Comment by leisim** [comment]
Yes that looks promising but how would you handle a TTL greater than the runtime of the app?
It would need to be persisted and checked when the app is started again.

**Comment by Solido** [comment]
Also I'm not sure this approach is the best when you have a huge numbers of keys ...
If you have a hash you can have an external manager with timestamp, seems more efficient

**Comment by leisim** [comment]
> Correct, Also I'm not sure this approach is the best when you have a huge numbers of keys ...
If you have a hash you can have an external manager with timestamp, seems more efficient.

I agree...

> Completers would resume on the diff time now and previously calculated expiration timestamps.

Could you please explain that? I don't understand what you mean exactly.

**Comment by leisim** [comment]
I'm going to close this for now. I think a external solution would be easier to implement...
