### ISSUE TITLE
[QUESTION] query

### ISSUE THREAD

**Issue by ashkryab** [leisim/hive#19]
Can I replace sqlite to hive (SELECT * USERS WHERE ID > 0 AND gender LIKE "male" OR name LIKE "%ohn%" SORT BY age DESC )

Or this plugin work only with key-valur pair?

**Comment by ashkryab** [comment]
why do you compare with sqlite?

**Comment by leisim** [comment]
I compare it with SQLite because you can use Hive most of the time instead of SQLite.

You can do filtering in code. If you have a **very** large database, you should stick to SQLite.

**Comment by Nipodemos** [comment]
just to be sure, how much "very large" means?
1,000?
10,000?
100,000?
1,000,000?

i always wanted to know :smile:

**Comment by leisim** [comment]
Below 100.000 should be no problem for hive.

If your rely on filtering (which you have to do yourself), I wouldn't use more than 1000-5000.
