### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by GroovinChip** [leisim/hive#2]
When creating a new box, like so: `var box = await Hive.box('SettingsBox');` is `box` null until a value has been put into the box?

**Comment by leisim** [comment]
No it should be an instance of `Box`. There should also be a file `settingsbox.hive` created.

**Comment by GroovinChip** [comment]
Odd. I'm messing around with using Hive on Windows, and I'm using Provider to send a box down the widget tree. I create it in the root widget like so:
```
  var box;

  @override
  void initState() {
    makeBox();
    super.initState();
  }

  void makeBox() async {
    box = await Hive.box('SettingsBox');
    await box.put('defaultValue', 'default');
  }


  @override
  Widget build(BuildContext context) {
    return Provider<Box>(
      builder: (context) => box,
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(),
      ),
    );
  }
```

When I access it in a different widget, like so: `var box = Provider.of<Box>(context);`, Flutter tells me that it is null.

**Comment by leisim** [comment]
If I'm correct, the problem here is that `makeBox()` is not finished yet when `build()` tries to access the box. You don't await `makeBox()`. The problem is that in order to await `makeBox()`, `initState()` would need to be async which is not allowed.

I'm working on helpers for Flutter but until then you could use something like that:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: FutureBuilder<Box>(
        future: Hive.box('SettingsBox'),
        builder: (BuildContext context, AsyncSnapshot<Box> snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            return SomePage();
          } else {
            return Center(
              child: Text('Please wait'),
            );
          }
        },
      ),
    );
  }
}

class SomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var box = Hive['SettingsBox'];
    // Do whatever you like with the box
    return Center(
      child: Text('Your App content'),
    );
  }
}
```

Btw: you don't have to pass boxes. If you already opened it, you can get the box instance using `Hive['yourBoxName']`

**Comment by GroovinChip** [comment]
Okay, thank you very much!

**Comment by leisim** [comment]
I created a [basic example](https://github.com/leisim/hive/tree/master/examples/basic_flutter) if you are interested...

**Comment by GroovinChip** [comment]
Thanks!
