### ISSUE TITLE
Do you recommend any Unique Key Generator?

### ISSUE THREAD

**Issue by Nipodemos** [leisim/hive#22]
hello!
sorry for asking you for help instead of reporting an issue, but i don't know what to do now :sweat_smile: 

yesterday i was trying hive in a TODO  list app, and for each note i need to generate a unique key
i've used [UUID](https://pub.dev/packages/uuid) to generate a random key, but i faced an error of invalid arguments, problably i was doing something wrong. So, do you recommend any package or any method to generate a random key for each note ?

**Comment by leisim** [comment]
Hive supports autoIncrement keys. Just use `box.add()` instead of `box.put()`. Maybe that already helps.

Otherwise I don't have a good recommendation...

**Comment by Nipodemos** [comment]
thanks for the answer. I'll try that,
awesome work with this package :smile:
