### ISSUE TITLE
Is there a way to know if Hive was already initialized on device?

### ISSUE THREAD

**Issue by Nipodemos** [leisim/hive#23]
Hello,
i've red the examples and docs, and it seems that you alwals initialize hive when app starts.
Is there a way to know if it were already initialized?

Or it is not necessary?

**Comment by leisim** [comment]
No there isn't currently. If you call `Hive.init()` multiple times, nothing happens.

Do you need to know if it has been initialized?

**Comment by Nipodemos** [comment]
No no, i was just curios if calling init multiple times could be a bad thing. I'm glad that it isn't 
thank you for answer!
