### ISSUE TITLE
Hive.deleter(key) Does not delete over relaunches

### ISSUE THREAD

**Issue by haroldolivieri** [leisim/hive#26]
Calling `Hive.delete(key)`deletes the key when app is in use and keep working normally for changes on the box, but after killing and launching again `Hive` always fetches the last state before the key deletion.

**Open app first time**
-  Save value ["123"] into key
-  Save value ["1234"] into key
-  Fetch `box.get(key)` -> ["123", "1234"]
-  Call `Hive.delete(key)`
-  Fetch `box.get(key)` -> []

**_Kill app_**

**Relaunch app**
- Fetch `box.get(key)` -> ["123", "1234"] `// should be []`

**Comment by leisim** [comment]
Thanks for reporting. I'll investigate that.

**Comment by leisim** [comment]
I can reproduce the issue and I will fix it with the next version.

**Comment by leisim** [comment]
This is fixed in v0.5.0 but you'll need to clear the cache of your app.
