### ISSUE TITLE
Generate hive types from Protocol buffers

### ISSUE THREAD

**Issue by joeblew99** [leisim/hive#28]
I was reading about the way the types are modelled here: https://leisim.github.io/hive/#/generate_adapter

The numbering of each field is the exact same approach as GRPC / Protobufs.

SO i was thinking of writing a converter so that on the Server side you can reuse your protobufs to generate the hive types that the hive generator will use.

What do you think ?

**Comment by joeblew99** [comment]
My Use case is for CDC Architecture.

It works like this.

On Server you have a DB, It can be any DB.
When the data for a "View" changes you stream a CUD Event ( Create, Update, Delete) from the server to the Client ( Flutter ). Of course its only streamed to clients that have subscribed.
The CUD Event has:
a. a Change tpye ( Create, Update or Delete)
b. The data row.
These CUD events are modelled in your Server application tier as protobuf and so can be generated using hive generator. The use of protobufs ensures that everything is strongly typed but also that clients that have an old version do not break.

On the Client, the main Subscription handler receives all changes and then pushes them to the appropriate box ( one for each view) . The Hive watch then updates the graphical view.

Hope this helps.

**Comment by leisim** [comment]
You are correct, Hive type adapters are inspired by protobuf and work almost exactly the same.

Your approach sounds very interesting and I'd love to see if it actually works.

This is not something I want to implement for Hive itself but you could create a package. If you need any help / support just contact me.

**Comment by joeblew99** [comment]
yes its not something i expected to be put into this project.
I was wanting feedback about my presumptions, and it seems i was on the right track.

I will close this and get back to you if i get stuck.

**Comment by aghil4u** [comment]
hii.... just would like to know is such an adapter have been made... i find the perfomance of GRPC and Hive too good to keep them seperate. Thanks
