### ISSUE TITLE
To-Do App is broken

### ISSUE THREAD

**Issue by Nipodemos** [leisim/hive#29]
**Steps to Reproduce**
just entered your website.
Although that might be because i've tested your todo app before a few days or weeks ago, almost the same day you lauched that example. I don't know if that old information stored on my browser that caused this.
**Code sample**
instead i will provide a picture
![image](https://user-images.githubusercontent.com/11494727/64080249-3d91c680-ccc8-11e9-8c2b-f1ab9116c170.png)

**Version**
 - Platform: Web
 - Browser: Google Chrome

**Comment by leisim** [comment]
Please clear the cache of your browser. The binary format changed with the last version and old DBs don't work anymore...

**Comment by Nipodemos** [comment]
thanks for awnser 
i've done as you said and it worked perfect for me
![image](https://user-images.githubusercontent.com/11494727/64081807-5a37f980-ccdc-11e9-9044-f5950b5f5f78.png)
