### ISSUE TITLE
License Exception

### ISSUE THREAD

**Issue by MarcoMihaiCondrache** [leisim/hive#34]
**Steps to Reproduce**
Add hive as package to pubsec and call showLicensePage()
The license of hive package throw a exception in showLicensePage

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.7.8+hotfix 4
 - Hive version: 0.5.0

**Comment by leisim** [comment]
I just tested it with the counter example and the `showLicensePage()` method works fine for me. What error are you seeing?

**Comment by HiroyukTamura** [comment]
cf; https://github.com/flutter/flutter/issues/39723#issue-488438860

**Comment by MarcoMihaiCondrache** [comment]
> I just tested it with the counter example and the `showLicensePage()` method works fine for me. What error are you seeing?

Yes yes the page works but an exception is created in the console let me show you.

I send you a video that you can download [here](https://send.firefox.com/download/7007477647c1f0dc/#OEEOzxTwiSGvIzn2bypnHA)

**Comment by leisim** [comment]
I changed the license to the short version. I think it works now.
