### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by yaymalaga** [leisim/hive#36]
I know Hive isn't ready for production apps, but in my case I'm planning to use the library for caching purposes, so if the data is lost it isn't a big deal.

As I have seen breaking changes in the binary format, I would like to know how Hive manages these changes from version to version. Is the data just removed? Is there anything I should take into account?

**Comment by leisim** [comment]
There will be hopefully only one more version which breaks the binary format.
From version `1.0.0` onwards this will certainly never happen again or Hive will automatically migrate all your data.

If it happens now (before the first stable version) your app might crash until you clean the cache.

**Comment by yaymalaga** [comment]
So it's something you could handle for now with a try and catch to remove the box data, right?

**Comment by leisim** [comment]
Exactly

**Comment by yaymalaga** [comment]
Then no problem. Good luck with the 1.0.0 version, looking forward to use it!
