### ISSUE TITLE
Failing on writing Unicode Strings

### ISSUE THREAD

**Issue by re-bola** [leisim/hive#37]
I get the following exception `HiveError: String contains non-ASCII characters.` whenever I write a Unicode string (currently, I am just trying to store some Arabic text as a String in the database).

Any thoughts on how to fix this? I'm happy to implement the fix if you provide some pointers.

**Comment by leisim** [comment]
Keys have to be ASCII. Could you share a key value pair which is not working?

**Comment by re-bola** [comment]
Nevermind them. I made all the strings ascii and kept the values Unicode and it seems to work well.
Thank you for the quick feedback.

**Comment by hamza-sabri** [comment]
how did you do that?
am facing the same problem here whenever am trying to save Arabic string what should I do?

**Comment by viandmarket25** [comment]
To create your key, 
Use 
String.fromCharCode(key)
eg: 
var myKey=String.fromCharCode(key);

hiveBox.put(myKey,value);

then 
while fetching your values 

also retrieve your values by converting the non ASCII chars and pass as Key argument 

hiveBox.get(myKey,value);
Result
//my values

**Comment by TheMisir** [comment]
> how did you do that?
> am facing the same problem here whenever am trying to save Arabic string what should I do?

Hive only accepts ASCII characters as entry keys. But this limitation does not applies to values.

```dart
box.put('non-ascii-key', '...');                 // will not work
box.put('ascii-key', 'non-ascii-value'); // will work
```

**Comment by viandmarket25** [comment]
Use this
Make sure to 

import dart:convert;

Convert your key to ascii code 
Eg:
//your key is probably an unaccepted string 

Var myKey= key.codeUnitAt(0);
Then,
hiveBox.put(myKey,values);

To retrieve your values Do the same thing, 
Var myKey=key.codeUnitAt(0);
Then,
hiveBox.get(myKey);

//results your values

**Comment by viandmarket25** [comment]
If it works for you, lemme know if it doesn't also lemme know with your error logs to help better

**Comment by TheMisir** [comment]
Anyways posting error logs will help to better understand the issue.
