### ISSUE TITLE
Add hive to Flutter Arsenal

### ISSUE THREAD

**Issue by flutter-arsenal** [leisim/hive#42]
hive can be added to FlutterArsenal to help with reach, accessibility and ease-of-use. [Flutter Arsenal](https://flutterarsenal.com) is a directory that is being curated for Flutter libraries and tool. The best way to do is by creating an issue on [github](https://github.com/flutterarsenal/FlutterArsenal/issues/new/choose).

**Comment by leisim** [comment]
Cool, Thanks! Should I do that or are you adding it?
