### ISSUE TITLE
[Feature Request] Generic Types for Box

### ISSUE THREAD

**Issue by Afsar-Pasha** [leisim/hive#45]
It would be great if `Box` support generic types such as `Box<K, V>`.

**Comment by leisim** [comment]
What exactly do you mean? You can store any object in a box.

**Comment by Afsar-Pasha** [comment]
Ex, if I want a box to store only `String` keys then, by using `Hive.openBox<dynamc, String>('box')` compiler would allow only to write `String` as value in `Box.put, Box.putAt, etc`.
This could reduce bugs, and also compiler can understand the return type of Box.get(key).

**Comment by leisim** [comment]
This only works with values because the `add()` method implicitly stores an integer key.
So if you would open a box which only supports String keys and you use the `add()` method, there will be an exception.
I'm not sure if the users expect that...

**Comment by Afsar-Pasha** [comment]
Maybe `Box<T>` in which value is T and key is always dynamic?

**Comment by leisim** [comment]
I'll implement that :+1:

**Comment by leisim** [comment]
I thought about this and (afaik) it is impossible to implement this. The best example are lists: You cannot cast `List<dynamic>` to `List<SomeObject>` so if you open a box of type `Box<List<SomeObject>>`, you expect to get a `List<SomeObject>` if you call `box.get('myKey')` but you actually get a `List<dynamic>`.

If you have a solution for this problem, I would happily implement this feature.

**Comment by Afsar-Pasha** [comment]
I think it can be implemented by using [this approach](https://stackoverflow.com/a/28556110) but that would require a little bit of boilerplate and that would be hacky, so closing this issue. Would re-open if I got any neat solution.

**Comment by Afsar-Pasha** [comment]
Instead of that [approach](https://stackoverflow.com/a/28556110) we can add an anonymous function to convert List and Map such as
```dart
Hive.openBox<List<int>>('box', toList: (l)=>l.cast<int>().toList())
``` 
in `BoxImpl`
```dart
T Function(List<dynamic> l) castToList;
T Function(Map<dynamic, dynamic> m) castToMap;
BoxImpl(... , {this.castToList, this.castToMap} ...) //constructor
...
  T get(dynamic key, {T defaultValue}){
  ...
    if(frame.value is List)
      return castToList(frame.value);
    if(frame.value is Map)
      return castToMap(frame.value);
```
but still requires some boilerplate and a  little bit confusing.

**Comment by leisim** [comment]
Unfortunately `cast()` only works for "one dimension". `List<List<dynamic>>.cast<List<List<int>>()` will fail.

I think this is a major flaw of the language :/

**Comment by Afsar-Pasha** [comment]
I mean they can provide a function to convert `List<dynamic>` to `List<T>` for that, the function can be
```dart
(list) => (l.map((l) => l.cast<int>().toList()).toList().cast<List<int>>().toList())
```
