### ISSUE TITLE
[Feature Request] Easy to sync with back end server

### ISSUE THREAD

**Issue by leedstyh** [leisim/hive#7]
Hi,

Hive is great, and I wanna use it in a <del>mobile-first</del> offline-first app. So I have to sync data with my back-end server silently.

My app will encrypt user data and since Hive already does it, the best way is sync the encrypted string(or what ever binary format)  to the server. So I need a method to get this encrypted string. 

Maybe additional methods like `Future<void> putRaw(String k, String v)` and `Future<String> getRaw(String k)` are good choice?

**Comment by leisim** [comment]
Hi,
Do want to backup a box or do you want to decrypt and use the data on the server?

Every encrypted entry also contains an [IV](https://en.wikipedia.org/wiki/Initialization_vector) without that, the entry cannot be decrypted.

What would `putRaw()` and `getRaw()` do exactly? And what would `getRaw()` return for other objects?

**Comment by leedstyh** [comment]
Hi, 

I wanna backup the whole box, incrementally. Say I have 10 items total in the box now, after changing one item (`box.put('myDog', dog)`), I sync it to the server right away. Or one item changed on the server, I need to sync the changed one to the client app.

I wanna encrypt the user data both on client app and server, and since Hive already encrypt data, I think reuse it is a good idea.

So what transferred between client app and server is NOT `dog`, but the dog after encrypted. I'm not sure but I assume it's a String(`"xxxooo"`) stored on the storage after `dog` encrypted.

`Future<String> box.getRaw("myDog")` returns that String(`"xxxooo"`) and I sync this String(`"xxxooo"`) to the server.

`Future<void> putRaw("myDog", "xxxooo from server")` save the change from the server directly.

Sorry that I'm not good at English.

**Comment by leisim** [comment]
Okay I understand... The problem is that Hive stores objects as `Uint8List` when running in the vm. In the browser, only non primitive and encrypted values are stored as `Uint8List`. I don't know what `getRaw()` should return. A string is impossible because of the IV.

I think the best way is to transfer the data unencrypted over HTTPS and handle encryption on the server (maybe even with another hive ;).

You would have to sync the value, the IV and the encryption key otherwise.

**Comment by leedstyh** [comment]
I got it. But encrypt and decrypt both on client and server will waste too much CPU :(

I can encrypt the data to a string by myself, and save this string in hive(`box.put("myDog", "encrypted string")`). And I register a TypeAdapter say `LongString` for it in case the encrypted string is too long.

Do you think it is a good idea?

**Comment by leisim** [comment]
Sure you can do that but unless you change the data **very often** I would not worry about CPU usage. The AES algorithm Hive uses is quite fast.

**Comment by leedstyh** [comment]
Thanks @leisim I'll double think how to design my app

**Comment by ThinkDigitalSoftware** [comment]
Won't transferring it unencrypted leave you vulnerable for mitm attacks?

**Comment by adriancmurray** [comment]
@ThinkDigitalSoftware this is why @leisim specified transferring over HTTPS to encrypt over the channels. The encryption here is so those who have direct access to the data can not read it (such as us developers) unless trusted.

**Comment by ThinkDigitalSoftware** [comment]
Oh that makes sense.

**Comment by jamesdixon** [comment]
@adriancmurray what approach did you end up taking? looking to rebuild my app and it definitely needs to be offline-first so im exploring options for persistence, including hive.
