### ISSUE TITLE
Store a list of my own class?

### ISSUE THREAD

**Issue by krypticallusion** [leisim/hive#8]
How do I store a list of my class `myClass`?

I get an error {
 ``` Cannot write unknown data type : myClass```
}

Thanks.

**Comment by leisim** [comment]
You have to use [TypeAdapters](https://leisim.github.io/hive/#/type_adapters). You can either create it yourself or use `hive_generator` to [generate it automatically](https://leisim.github.io/hive/#/generate_adapter).

**Comment by aswinmohanme** [comment]
What command should I use to run the hive_generator ? Can't find it on the docs

**Comment by leisim** [comment]
Try `flutter pub run build_runner build`

**Comment by aswinmohanme** [comment]
I had to add build_runner package too, I will update the docs and send a PR :D

**Comment by leisim** [comment]
Oh thanks 👍👍

**Comment by leisim** [comment]
@krypticallusion if you need more help, just reopen the issue.
